apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: card-replacer-web:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_APP
              value: "run.py"
            - name: FLASK_ENV
              value: "development"
            - name: DATABASE_URL
              value: "postgresql://card_user:password@postgres/card_request_db"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "card_user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: CELERY_BROKER_URL
              value: "redis://redis:6379/0"
            - name: CELERY_RESULT_BACKEND
              value: "redis://redis:6379/0"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80        # The port your service will use inside the cluster
      targetPort: 5000 # The port your Flask app is listening on
      nodePort: 30000  # <-- Specify a fixed NodePort here (e.g., 30000)
  type: NodePort
